import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import PromptInput from "@/components/PromptInput";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI art Gallery",
  description: "Generated by Yosua",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <PromptInput />
          {children}
        </Providers>
      </body>
    </html>
  );
}
